// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// eta_post_cpp
double eta_post_cpp(const Rcpp::NumericVector& x, const Rcpp::List& pars);
RcppExport SEXP _DSSP_eta_post_cpp(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(eta_post_cpp(x, pars));
    return rcpp_result_gen;
END_RCPP
}
// make_M
Rcpp::List make_M(const Rcpp::NumericMatrix& x);
RcppExport SEXP _DSSP_make_M(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(make_M(x));
    return rcpp_result_gen;
END_RCPP
}
// sample_delta_cpp
arma::vec sample_delta_cpp(const Rcpp::NumericVector& x, const Rcpp::List& pars);
RcppExport SEXP _DSSP_sample_delta_cpp(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_delta_cpp(x, pars));
    return rcpp_result_gen;
END_RCPP
}
// sample_nu_cpp
arma::mat sample_nu_cpp(const Rcpp::NumericVector& x, const Rcpp::List& pars);
RcppExport SEXP _DSSP_sample_nu_cpp(SEXP xSEXP, SEXP parsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type pars(parsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_nu_cpp(x, pars));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DSSP_eta_post_cpp", (DL_FUNC) &_DSSP_eta_post_cpp, 2},
    {"_DSSP_make_M", (DL_FUNC) &_DSSP_make_M, 1},
    {"_DSSP_sample_delta_cpp", (DL_FUNC) &_DSSP_sample_delta_cpp, 2},
    {"_DSSP_sample_nu_cpp", (DL_FUNC) &_DSSP_sample_nu_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DSSP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
