# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eta_post_cpp <- function(x, pars) {
    .Call(`_DSSP_eta_post_cpp`, x, pars)
}

make_M <- function(x) {
    .Call(`_DSSP_make_M`, x)
}

rcpparma_hello_world <- function() {
    .Call(`_DSSP_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_DSSP_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_DSSP_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_DSSP_rcpparma_bothproducts`, x)
}

sample_delta_cpp <- function(x, pars) {
    .Call(`_DSSP_sample_delta_cpp`, x, pars)
}

sample_nu_cpp <- function(x, pars) {
    .Call(`_DSSP_sample_nu_cpp`, x, pars)
}

