# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

preeta <- function(x, pars) {
    .Call('_DSSP_preeta', PACKAGE = 'DSSP', x, pars)
}

create_xptr <- function(fstr) {
    .Call('_DSSP_create_xptr', PACKAGE = 'DSSP', fstr)
}

